language: python
services:
  - docker
python:
  - "2.7"

install:
  - make deps

script:
  - make test
- make lint
- make test_xunit

after_success:
  - make docker_build
  - make docker_push
deploy:
  provider: heroku
  app: radiant-lowlands-20113
  api_key: ${HEROKU_API_KEY}
